version: "3.7"

services:
  db:
    image: postgres
    container_name: db_rentlx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentlx
    volumes:
      - pgdata:/data/postgres
  # app:
  #   build: .
  #   container_name: rentlx
  #   ports: 
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - db
  #   depends_on:
  #     - db

volumes:
  pgdata:
    driver: local